"use client";
import React from "react";
import Image from "next/image";
import { Button } from "../button";
import { Code, Monitor, Smartphone } from "lucide-react";
import { useEmailTemplate, useScreenSize } from "@/app/Provider";
import { useMutation } from "convex/react";
import { api } from "@/convex/_generated/api";
import { useParams } from "next/navigation";
import { toast } from "sonner";
import Link from "next/link";

function EditorHeader({ viewHTMLCode,htmlCode , getLatestHtml}) {
  const { screenSize, setScreenSize } = useScreenSize();
  const updateEmailTemplate = useMutation(
    api.emailTemplate.UpdateTemplateDesign
  );
  const { templateId } = useParams();
  const {emailTemplate,setEmailTemplate}=useEmailTemplate()
  const onSaveTemplate = async () => {
    await updateEmailTemplate({
      tid: templateId,
      design:emailTemplate
    });
    toast('Email Template Saved Successfully!')
  };



const sendTestEmail = async () => {
  const html=getLatestHtml()
  const recipientEmail = prompt("Enter your email address:");
  if (!recipientEmail) return;
console.log("HTML code being sent:", htmlCode);

  const response = await fetch("/api/send-test-email", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      to: recipientEmail,
      htmlContent: html, // The HTML email content generated by your AI
    }),
  });

  const data = await response.json();

  if (response.ok) {
    alert("Test email sent successfully!");
  } else {
    alert(data.error || "Failed to send email. Try again.");
  }
};





  return (
    <div className="p-4 shadow-sm flex justify-between items-center">
      <Link href={'/dashboard'}>
      <Image src={"/logo.svg"} width={100} height={100} alt="logo"></Image>
      </Link>
      <div className="flex gap-3">
        <Button
          onClick={() => setScreenSize("Desktop")}
          variant="ghost"
          className={`${screenSize == "Desktop" && "bg-purple-100 text-primary"}`}
        >
          <Monitor />
          Desktop
        </Button>

        <Button
          onClick={() => setScreenSize("mobile")}
          variant="ghost"
          className={`${screenSize == "mobile" && "bg-purple-100 text-primary"}`}
        >
          <Smartphone /> Mobile
        </Button>
      </div>
      <div></div>
      <div className="flex gap-3">
        <Button
          variant="ghost"
          className="hover:text-primary hover:bg-purple-100"
          onClick={() => viewHTMLCode(true)}
        >
          <Code />
        </Button>
        <Button variant="outline" onClick={sendTestEmail}>Send Test Email</Button>
        <Button onClick={onSaveTemplate}>Save Template</Button>
      </div>
    </div>
  );
}

export default EditorHeader;
