"use client";
import React from "react";
import Image from "next/image";
import { Button } from "../button";
import { Code, Monitor, Smartphone } from "lucide-react";
import { useEmailTemplate, useScreenSize } from "@/app/Provider";
import { useMutation } from "convex/react";
import { api } from "@/convex/_generated/api";
import { useParams } from "next/navigation";
import { toast } from "sonner";
import Link from "next/link";

function EditorHeader({ viewHTMLCode, htmlCode, getLatestHtml }) {
  const { screenSize, setScreenSize } = useScreenSize();
  const updateEmailTemplate = useMutation(
    api.emailTemplate.UpdateTemplateDesign,
  );
  const { templateId } = useParams();
  const { emailTemplate, setEmailTemplate } = useEmailTemplate();
  const onSaveTemplate = async () => {
    // 1. Define a Deep Clean function
    const formatDesign = (design) => {
      // If design is null/undefined, return it
      if (!design) return design;

      // Loop through each item (Layout)
      return design.map((item) => {
        // Create a copy of the item so we don't mutate state directly
        const newItem = { ...item };
        delete newItem.icon;
        Object.keys(newItem).forEach((key) => {
          if (Array.isArray(newItem[key])) {
            // If we find an array (like columns/elements), clean the items inside it
            newItem[key] = formatDesign(newItem[key]);
          }
        });

        return newItem;
      });
    };

    // 2. Clean the data deeply
    const designToSave = formatDesign(emailTemplate);

    console.log("Saving Design:", designToSave); // Debugging log

    // 3. Save the clean data
    await updateEmailTemplate({
      tid: templateId,
      design: designToSave,
    });

    // toast("Template Saved Successfully!");
  };

  const sendTestEmail = async () => {
    const html = getLatestHtml();
    const recipientEmail = prompt("Enter your email address:");
    if (!recipientEmail) return;
    console.log("HTML code being sent:", htmlCode);

    const response = await fetch("/api/send-test-email", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        to: recipientEmail,
        htmlContent: html, // The HTML email content generated by  AI
      }),
    });

    const data = await response.json();

    if (response.ok) {
      alert("Test email sent successfully!");
    } else {
      alert(data.error || "Failed to send email. Try again.");
    }
  };

  return (
    <div
      className="p-4 shadow-sm flex justify-between items-center"
      suppressHydrationWarning
    >
      <Link href={"/dashboard"}>
        <Image src={"/logo.svg"} width={100} height={100} alt="logo"></Image>
      </Link>
      <div className="flex gap-3">
        <Button
          onClick={() => setScreenSize("Desktop")}
          variant="ghost"
          className={`${screenSize == "Desktop" && "bg-purple-100 text-primary"}`}
        >
          <Monitor />
          Desktop
        </Button>

        <Button
          onClick={() => setScreenSize("mobile")}
          variant="ghost"
          className={`${screenSize == "mobile" && "bg-purple-100 text-primary"}`}
        >
          <Smartphone /> Mobile
        </Button>
      </div>
      <div></div>
      <div className="flex gap-3">
        <Button
          variant="ghost"
          className="hover:text-primary hover:bg-purple-100"
          onClick={() => viewHTMLCode(true)}
        >
          <Code />
        </Button>
        <Button variant="outline" onClick={sendTestEmail}>
          Send Test Email
        </Button>
        <Button onClick={onSaveTemplate}>Save Template</Button>
      </div>
    </div>
  );
}

export default EditorHeader;
